### ISSUE TITLE
Mesos Web interface and Compatibility View on Windows Jumpbox

### ISSUE THREAD

**Issue by lawrencegripper** [anhowe/mesos-scalable-cluster#1]
The default for IE is to use compatibility view for intranet sites, this causes issues with the web interface for Mesos and Marathon (they don't work). 

Is it worth adding a note into the guide to show users how to disable this so all works first time round?

![image](https://cloud.githubusercontent.com/assets/1939288/9814524/c38cc970-5886-11e5-8268-36328c7d0fe3.png)

**Comment by anhowe** [comment]
Thanks for the feedback! I'll add this.

**Comment by lawrencegripper** [comment]
Np, looks good - thanks for the cluster.

**Comment by anhowe** [comment]
I've now added an extension to ensure Internet Explorer is always has this disabled and opens to the mesos master page by default.
