### ISSUE TITLE
Windows Jumpbox Deployment fails

### ISSUE THREAD

**Issue by lawrencegripper** [anhowe/mesos-scalable-cluster#3]
Hi, 

Appears to be related to adding the SSH key parameter to the template

![image](https://cloud.githubusercontent.com/assets/1939288/10046661/07aeab12-6202-11e5-86b6-f0ee0ee66e50.png)

**Comment by anhowe** [comment]
thanks Lawrence, I've uploaded a fix and testing now.  I'll update once I have verified this is fixed.
